# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sklm_to_scorer": "metrics.ipynb",
         "R2Score": "metrics.ipynb",
         "MSEScore": "metrics.ipynb",
         "MAEScore": "metrics.ipynb",
         "BalancedAccuracyScore": "metrics.ipynb",
         "MatthewsCorrCoef": "metrics.ipynb",
         "PrecisionScore": "metrics.ipynb",
         "RecallScore": "metrics.ipynb",
         "FBetaScore": "metrics.ipynb",
         "ROCAucScore": "metrics.ipynb",
         "APScore": "metrics.ipynb"}

modules = ["metrics.py"]

doc_url = "https://marcossantanaioc.github.io/mlmetrics/"

git_url = "https://github.com/marcossantanaioc/mlmetrics/tree/master/"

def custom_doc_links(name): return None
